services:
  # NGINX
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - nginx
    depends_on:
      - api-gateway

  # PROMETHEUS
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:9090 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - monitoring

  # GRAFANA
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:3000/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - monitoring

  # ELK STACK
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xms512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - elk-stack

  logstash:
    image: logstash:8.15.2
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m  -Xms256m"
    ports:
      - "5000:5000/tcp"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9600/_node/pipelines || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s
    networks:
      - elk-stack
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: kibana:8.15.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    networks:
      - elk-stack
    depends_on:
      elasticsearch:
        condition: service_healthy

  # REDIS
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6380"
    volumes:
      - ./redis:/data
    command: --port 6380
    networks:
      - redis
    restart: always

  # RABBITMQ
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - rabbitmq
    restart: always

  # ZIPKIN
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - tracing
    restart: always

  # POSTGRES DATABASES
  postgres-auth:
    image: postgres:alpine
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-service
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - postgres
    restart: always

  postgres-user:
    image: postgres:alpine
    container_name: postgres-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-management-service
    ports:
      - "5434:5434"
    command: -p 5434
    networks:
      - postgres
    restart: always

  postgres-patient:
    image: postgres:alpine
    container_name: postgres-patient
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient-service
    ports:
      - "5435:5435"
    command: -p 5435
    networks:
      - postgres
    restart: always

  postgres-report:
    image: postgres:alpine
    container_name: postgres-report
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: report-service
    ports:
      - "5436:5436"
    command: -p 5436
    networks:
      - postgres
    restart: always

  # MAIN SERVICES
  config-server:
    container_name: config-server
    image: omerasafbalikci/config-server:latest
    ports:
      - "8888:8888"
    volumes:
      - ./logs:/logs
    networks:
      - elk-stack

  discovery-server:
    container_name: discovery-server
    image: omerasafbalikci/discovery-server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    volumes:
      - ./logs:/logs
    networks:
      - elk-stack
      - discovery
      - tracing
    depends_on:
      config-server:
        condition: service_started
      logstash:
        condition: service_healthy
      zipkin:
        condition: service_started

  api-gateway:
    container_name: api-gateway
    image: omerasafbalikci/api-gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080"
    volumes:
      - ./logs:/logs
    networks:
      - elk-stack
      - discovery
      - tracing
      - redis
      - nginx
    depends_on:
      - discovery-server
      - redis

  auth-service:
    container_name: auth-service
    image: omerasafbalikci/auth-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/logs
    networks:
      - elk-stack
      - discovery
      - postgres
      - tracing
      - redis
      - rabbitmq
    depends_on:
      - api-gateway
      - rabbitmq
      - postgres-auth

  user-service:
    container_name: user-service
    image: omerasafbalikci/user-management-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/logs
    networks:
      - elk-stack
      - discovery
      - postgres
      - tracing
      - rabbitmq
    depends_on:
      - api-gateway
      - auth-service
      - postgres-user

  patient-service:
    container_name: patient-service
    image: omerasafbalikci/patient-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/logs
    networks:
      - elk-stack
      - discovery
      - postgres
      - redis
      - tracing
    depends_on:
      - postgres-patient
      - api-gateway

  report-service:
    container_name: report-service
    image: omerasafbalikci/report-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/logs
    networks:
      - elk-stack
      - discovery
      - postgres
      - redis
      - tracing
    depends_on:
      - postgres-report
      - patient-service
      - api-gateway

networks:
  discovery:
  nginx:
  elk-stack:
  postgres:
  redis:
  tracing:
  monitoring:
  rabbitmq: