spring:
  application:
    name: api-gateway
  cloud:
    config:
      label: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    hostname: api-gateway

route:
  auth: "lb://auth-service"
  user: "lb://user-management-service"
  patient: "lb://patient-service"
  report: "lb://report-service"

redis:
  host: "redis"
  port: "6380"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
