spring:
  application:
    name: patient-service

server:
  port: 8083

logging:
  level:
    org.springframework.data.redis: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
