spring:
  application:
    name: patient-service
  redis:
    host: "localhost"
    port: "6379"

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka