spring:
  application:
    name: report-service
  cloud:
    config:
      label: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    hostname: report-service

pdf:
  font-path: "fonts/times.ttf"
  image-path: "/static/images/sevda.png"
  hospital-name: "SEVDA HASTANESİ"

prescription:
  font-path:
    light: "fonts/rubik-light.ttf"
  image-path:
    gemini: "/static/images/gemini.png"
    symbol: "/static/images/symbol.png"

gemini:
  api-key: "AIzaSyAkvVnN7b4nmTwYkrtgV729Vbb5i0r0pt8"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

